name: Build Docker image

on:
    schedule:
        # run every month
        - cron: '0 0 1 * *'
    push:
        branches: master
        tags:
            - v*

env:
    DOCKER_IMAGE: mammo0/docker-webdav
    DOCKER_PLATFORMS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Check scheduled release
              if: github.event_name == 'schedule'
              run: |
                  # checkout the latest release
                  git fetch --tags --all
                  git checkout $(git tag --list 'v*' --sort=v:refname |tail -1)

            - name: Prepare environment
              id: prepare
              run: |
                echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v3
              with:
                images: ${{ env.DOCKER_IMAGE }}
                tags: |
                  type=edge,branch=master
                  type=schedule,pattern=edge
                  type=schedule,pattern=latest
                  type=ref,event=tag

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                context: .
                build-args: |
                  BUILD_DATE=${{ steps.prepare.outputs.build_date }}
                platforms: ${{ env.DOCKER_PLATFORMS }}
                push: true
                tags: ${{ steps.meta.outputs.tags }}
